### ISSUE TITLE
AuthorRetrieval: Numeric values stored as string

### ISSUE THREAD

**Issue by ale-de-vries** [pybliometrics-dev/pybliometrics#122]
Numeric values in the object returned by AuthorRetrieval are stored as string:
```
>>> type(author_1_full.document_count))
<class 'str'>
>>> type(author_1_full.cited_by_count)
<class 'str'>
>>> type(author_1_full.citation_count)
<class 'str'>
>>> type(author_1_full.h_index)
<class 'str'>
```
This means that before being able to do comparison or computation, the user needs to cast these value to int or float. Better would be to store them as int/float natively.

**Comment by Michael-E-Rose** [comment]
Hi! Yes, they are all strings (like in all the other classes as well) because that's how it comes out of the json.

I guess we can do the service to the user and change the type to `int`.  But then it should be across generally, across all the classes.

Do you want to put together a PR?  I guess it will be a simple one.  It's just important to mind the tests which need updates as well.
