### ISSUE TITLE
Implement X-RateLimit-Reset

### ISSUE THREAD

**Issue by Michael-E-Rose** [pybliometrics-dev/pybliometrics#129]
From the Elsevier developer news: "The Elsevier APIs return a set of response headers designed to help developers know when they are within the quota settings for a given APIKey."

We should implement this.

**Comment by ioggstream** [comment]
It would be great if this implementation relied on the [new ratelimit standardization proposal](https://tools.ietf.org/id/draft-polli-ratelimit-headers-01.html).

The proposal was:
-  recently presented at the [HTTP Workgroup during the IETF Meeting](http://bit.ly/2qWhwwD)
- implemented by Kong
- under implementation in 3scale

## The proposal

Very similar to your current implementation, but  header names have no `X-` and `Reset` is in `delta-seconds` instead of timestamp. The rationale for the choice is in [FAQ 5](https://ioggstream.github.io/draft-polli-ratelimit-headers/draft-polli-ratelimit-headers.html#rfc.appendix.D).

```
RateLimit-Limit: 60
RateLimit-Remaining: 50
RateLimit-Reset: 5
```

**Comment by Michael-E-Rose** [comment]
Thanks for the information. They come timely, because I wanted to tackle this issue early next month.

Though, I am bounded to what the Scopus API offers me. I cannot set the ratelimit or anything. Probably you wanted to reach the Scopus developers?

**Comment by ioggstream** [comment]
Thanks Michael, can you point me to somebody in that organization?

**Comment by Michael-E-Rose** [comment]
I've got absolutely no idea! My experience with Scopus however tells me, that emails you send via the Scopus web form eventually reach the intended audience. In this case, this would be the integration service.
