### ISSUE TITLE
Data inconsistency

### ISSUE THREAD

**Issue by Yousra-Regaya** [pybliometrics-dev/pybliometrics#136]
I tried to fetch a list of publications for a list of authors from 3 different laptops, and at each time I am getting a different number of records.
Does anyone have an explanation for this matter? and is there a way to solve this issue?

The query that I am using is:
search_results = ScopusSearch('AU-ID ({}) AND AFFIL (University_Name)'.format(author_id))

**Comment by Michael-E-Rose** [comment]
The most obvious explanation is that you sourced the results at different points in time and in between Scopus updated the records. Since pybliometrics uses cached files when available, you're seeing old results. Setting `refresh=True` would override this behaviour.

Can you please write here which exact query you're using and how many results you're getting on each machine?
