### ISSUE TITLE
author_count counts also the repetitions

### ISSUE THREAD

**Issue by raffaem** [pybliometrics-dev/pybliometrics#169]
```
> from pybliometrics.scopus import ScopusSearch
> s = ScopusSearch("DOI(10.1017/S0021932020000243)")
> len(s.results[0].author_names.split(";"))
7
> s.results[0].author_count
13
```

If you go on the [Scopus page](https://www.scopus.com/record/display.uri?eid=2-s2.0-85087014934&origin=resultslist) of the publication, 13 authors are listed by Scopus, but 6 of them are repetitions of the same name, resulting in an effective total of 13-6 = 7 authors.

But why `author_count` also counts also the repetitions? Should it be specified in the [documentation](https://pybliometrics.readthedocs.io/en/stable/reference/pybliometrics.ScopusSearch.html)?

P.S.
The documentation states that

> Field definitions correspond to https://dev.elsevier.com/guides/ScopusSearchViews.htm, except for afid, affilname, affiliation_city, affiliation_country, **author_count**, author_names, author_ids and author_afids: These information are joined on “;”.

It is not true that `author_count` is joined on ";"

**Comment by Michael-E-Rose** [comment]
You, sir, surely have an eye for rare weird entries :D

The problem is in Scopus:

```
>>> from pybliometrics.scopus import AbstractRetrieval
>>> ab = AbstractRetrieval("2-s2.0-85087014934", view="FULL")
>>> for a in ab.authors:
...  print(a.auid)
... 
57194579659
57194579659
6603109253
7401971749
7401971749
6602423911
9739700800
9739700800
37002652000
37002652000
37002652000
6701871391
6701871391
```

The `author_count` variable you see ScopusSearch() returns the value as is, directly from the Scopus Search API.  It is pybliometrics' iron rule to return the data as is and not mingle with the values.  Otherwise one doesn't know where to stop and eventually lands in Hell's Kitchen.
Documentation however can surely benefit from an extra word, even though this example is very rare.  I suspect that Scopus fixes this as soon as the article is fully published (and not in-press any more).

Regarding the PS: Yes, that is wrong.  Nice catch!  Will fix that.
