### ISSUE TITLE
ScopusSearch limits and Scopus429Error 

### ISSUE THREAD

**Issue by NastyaSNK** [pybliometrics-dev/pybliometrics#192]
The exception pybliometrics.scopus.exception.Scopus429Error comes when I made small changes in request. 
The query below works well
`ScopusSearch('TITLE-ABS-KEY( educat*  OR  learn*  OR  teach  OR  student* )  AND  SUBJAREA ( soci )  AND  PUBYEAR  >  2020')`
This query returns Scopus429Error
`ScopusSearch('TITLE-ABS-KEY( educat*  OR  learn*  OR  teach  OR  student* )  AND  SUBJAREA ( soci )  AND  PUBYEAR  is  2020')`
Here is the output:
```
Scopus429Error                            Traceback (most recent call last)
<ipython-input-28-39753b857c27> in <module>
----> 1 ScopusSearch('TITLE-ABS-KEY( educat*  OR  learn*  OR  teach  OR  student* )  AND  SUBJAREA ( soci )  AND  PUBYEAR  is  2020')

C:\ProgramData\Anaconda3\lib\site-packages\pybliometrics\scopus\scopus_search.py in __init__(self, query, refresh, subscriber, view, download, integrity_fields, integrity_action, verbose, **kwds)
    200         # Query
    201         self.query = query
--> 202         Search.__init__(self, query=query, api='ScopusSearch', refresh=refresh,
    203                         count=count, cursor=subscriber, view=view,
    204                         download=download, verbose=verbose, **kwds)

C:\ProgramData\Anaconda3\lib\site-packages\pybliometrics\scopus\superclasses\search.py in __init__(self, query, api, refresh, view, count, max_entries, cursor, download, verbose, **kwds)
     75         else:
     76             params.update({'start': 0})
---> 77         Base.__init__(self, qfile, refresh, params=params, url=SEARCH_URL[api],
     78                       download=download, max_entries=max_entries, verbose=verbose)
     79         # Set query parameters

C:\ProgramData\Anaconda3\lib\site-packages\pybliometrics\scopus\superclasses\base.py in __init__(self, fname, refresh, params, url, download, max_entries, verbose, *args, **kwds)
     69                     self._json = loads(f.read().decode('utf-8'))
     70         else:
---> 71             resp = get_content(url, params, *args, **kwds)
     72             header = resp.headers
     73             if search_request:

C:\ProgramData\Anaconda3\lib\site-packages\pybliometrics\scopus\utils\get_content.py in get_content(url, params, *args, **kwds)
     86             except:
     87                 reason = ""
---> 88         raise errors[resp.status_code](reason)
     89     except KeyError:
     90         resp.raise_for_status()
Scopus429Error: 
```

Does it mean that I exceed week query limits? Is ScopusSearch(some_query) a one query for scopus?

**Comment by Michael-E-Rose** [comment]
Yes to both questions.

Have you registered 10 keys with your account? pybliometrics will cycle through them until all of them have reached their quota.

**Comment by NastyaSNK** [comment]
I've got two register Api keys with inst token. And I use just one of them for connection (it defines in config.yml)

If I exceeded the query limit, why `ScopusSearch('TITLE-ABS-KEY( educat* OR learn* OR teach OR student* ) AND SUBJAREA ( soci ) AND PUBYEAR > 2020')` still return the respond after Scopus429Error with another query?

**Comment by Michael-E-Rose** [comment]
Because once completed, query results are stored in your local cache. See for example https://pybliometrics.readthedocs.io/en/stable/reference/pybliometrics.ScopusSearch.html:

> The directory for cached results is {path}/{view}/{fname}, where path is specified in ~/.scopus/config.ini and fname is the md5-hashed version of query.

or https://pybliometrics.readthedocs.io/en/stable/examples/ScopusSearch.html at the end:

> Downloaded results are cached to speed up subsequent analysis. This information may become outdated. To refresh the cached results if they exist, set refresh=True, or provide an integer that will be interpreted as maximum allowed number of days since the last modification date. For example, if you want to refresh all cached results older than 100 days, set refresh=100. Use s.get_cache_file_mdate() to get the date of last modification, and s.get_cache_file_age() the number of days since the last modification.

**Comment by NastyaSNK** [comment]
If ScopusSearch(some_query) is a one query for Scopus, 429 error means that previously I made 5000 times ScopusSearch(some_query)? But I made maybe 15  unsuccessful attemts (year range was wider and the result was about 300 000 records) and after all this experiments I've got Scopus429Error.

**Comment by NastyaSNK** [comment]
Also if execute the next code: 

```
import requests
import json      
url = 'https://api.elsevier.com/content/search/scopus?apikey=c*b&query=AUTHFIRST%28John%29+AND+AUTHLASTNAME%28Kitchin%29+AND+SUBJAREA%28COMP%29'   
response = requests.get(url)
print(response.headers)
```

it returns headers with  'X-RateLimit-Limit': '20000', 'X-RateLimit-Remaining': '0'. And I think that it's an example of a response that still has something left of the quota:
`'Date': 'Mon, 03 May 2021 08:16:11 GMT', 'Content-Type': 'application/json', 'Content-Length': '225', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d41099072b17c2b219b812d6dfa99a0681620029770; expires=Wed, 02-Jun-21 08:16:10 GMT; path=/; domain=.elsevier.com; HttpOnly; SameSite=Lax', 'X-ELS-ReqId': '7451c474782432d1', 'X-ELS-TransId': 'ca4d6d1dcdfd255f', 'X-RateLimit-Limit': '20000', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1620518400', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '09d2e5a2b600008df9af99e000000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '64980bb118288df9-DME'`

If the quota has been exceeded the response should be: `{'Content-Encoding': 'gzip', 'Content-Type': 'text/xml;charset=UTF-8', 'Date': 'Fri, 19 Aug 2019 17:46:46 GMT', 'Server': 'Apache-Coyote/1.1', 'X-ELS-Status': 'QUOTA_EXCEEDED - Quota Exceeded', 'X-RateLimit-Reset': '2019-08-26 05:51:01', 'Content-Length': '191', 'Connection': 'keep-alive'}`

**Comment by Michael-E-Rose** [comment]
Ah sorry, I missunderstood your second question. `ScopusSearch(some_query)` counts as as many queries as there are results. If a query yields more results than one key can handle, pybliometrics immediately switches to the next one. Thus you can retrieve results for queries w/ more than 5k hits.

The reset information that you got there is also available through the methods `.get_key_remaining_quota()` and `.get_key_reset_time()`, that work on any class. It relates to the information on the last actual query (i.e. ignoring re-use of cached results).
Scopus always provides this information, which is why you can get information on depleted keys. Attempting to get data with a depleted key however results in 429 error - that's what the API returns, and not sth. that pybliometrics computes.

**Comment by NastyaSNK** [comment]
Now in config.yml i have one api key and one inst token. In cashe I've got a response with 30822 records. And 30k doesn't look like 5k limit. I also find an information that limits for ScopusSearch equl to 20k
![image](https://user-images.githubusercontent.com/29334459/116870953-26814580-ac1c-11eb-8b6d-000a5e6782d6.png)

**Questions**
1. If the limit is 5k records and in config.yml i have only 1 key how did I get the result with 30k records?
2. The methods .get_key_remaining_quota() and .get_key_reset_time() returns None for me. Interesting, that get_results_size() method returns an answer.

```
from pybliometrics.scopus import ScopusSearch
other_more2020 = ScopusSearch('TITLE-ABS-KEY( educat*  OR  learn*  OR  teach  OR  student* )  AND  SUBJAREA ( soci )  AND  PUBYEAR  >  2020', download=False)
print(other_more2020.get_key_reset_time())
print(other_more2020.get_key_remaining_quota())
print(other_more2020.get_results_size())
```
```
None
None
30822
```

Sorry for so many questions. I just try to understand the better way for extracting data for my research and I really struggle with how does limits work.

**Comment by Michael-E-Rose** [comment]
As explained, those two methods work on the last _actual_ API query. You said your query `'TITLE-ABS-KEY( educat*  OR  learn*  OR  teach  OR  student* )  AND  SUBJAREA ( soci )  AND  PUBYEAR  >  2020'` has been downloaded before and is thus in cache, right? So by retrieving these results, pybliometrics didn't access the APIs. Therefore the two methods return `None`.

Questions on the API quotas have come up before (e.g. #191), which is why I recently wrote a paragraph on it. It's not yet in the stable release: https://pybliometrics.readthedocs.io/en/latest/tips.html#api-key-quotas-and-429-error. It also links to the page you link.

I should also correct myself a little: It's not the number of results that matters, it's the number of _results pages_. For a query of 30,822 results in the COMPLETE view (the default in pybliometrics), you need 30,822/25 ~*1233* result pages. And that's the number of queries deducted from your key! If you used the STANDARD view, which offers less but allows for 200 results per results page, you'd need 30,822/200 ~ 155 results pages/queries. I presume you're a subscriber here.

I will also make this clearer in the documentation.

Since you speak about optimising the number of queries: We typically download information in a very granular way and then subset later. For example, we don't query `AU-ID(7004212771) AND PUBYEAR > 2010`, we'd just do `AU-ID(7004212771)` and subset on the publication range later. This increases the chances that the cached query can be reused.

**Comment by NastyaSNK** [comment]
1. If scopus gave me InstToken for register API keys  does it mean that I am a subscriber? I register scopus account as a student and after ask an InstToken for research.

2. For example I will use apikey+insttoken  and first query takes to me 30k results ~1233 pages(for not subscriber). I will save this result(download=True). After if I send next query with 4000 pages 429 error will return. But if the second query will include <=3767  pages it returns a data? 

3. I don't understand about optimization. I think that this request `AU-ID(7004212771)` will return more pages than `AU-ID(7004212771) AND PUBYEAR > 2010`, won't it?

3. If I've got one more key with InstToken, wich I didn't place at config.ini before, is it a chance for me to use it with optimized query and try it with standart mode (`ScopusSearch(query,subscriber=True,view='STANDARD')`) ,if i am a subscriber? Does it make sense to register additional api keys?

**Comment by Michael-E-Rose** [comment]
1. Yes I think you are a subscriber. InstToken would not make sense for non-subscriber, because then they would get more than they deserve. Essentially the InstToken substitutes for your institution's network that would normally provide you access. It is also my understanding that InstToken do not belong to API Keys. So you should be able to register all the 10 keys and use the same InstToken. Correct me if I'm wrong.
2. Yes.
3. Yes but that's a) not the entire story and b) not a very common outcome. First, a generic query like `AU-ID(7004212771)` is easy to re-use. Say one day you're interested in publications past 2010, and the next day you're interested in publications past 2016. With a generic query in the first place you don't need a second query. Also, the average number of publications of researchers is small and fits on one search page (i.e. less than 25). Even if it's more, it's very unlikely that you have to start a new search page just for one additional publication (i.e. publication no. 26).
4. It totally makes sense to register as many API keys and place them in the configuration file! When you're interested in more data with fewer details you should go for the STANDARD view, otherwise the COMPLETE view gives you more data.

**Comment by NastyaSNK** [comment]
Scopus representatives provided InsToken for each Apikey. So, I think that InstToken belongs to Apikey. Later I will test it.
Unfortunately one of my query provides large results, wich exceed limit (even for a standart view). That is why I use year filter in query.  I will also test the idea of creating 10 api keys later.

Thanks for your explanation. In the result my query works. And my manual limits calculation the same as the result wich provides with help of ` .get_key_remaining_quota() `

**Comment by Michael-E-Rose** [comment]
Yes it's true, it's one InstToken per API key. I was in the wrong. I need to adapt `config.ini` for this.

Glad it's working for you now!

**Comment by Michael-E-Rose** [comment]
Still no update on the InstToken-APIKey pairing because Scopus Integration Support still has not provided me with an InstToken.
