### ISSUE TITLE
[BUG] Paper published in 2021 has citations dated before 1900

### ISSUE THREAD

**Issue by raffaem** [pybliometrics-dev/pybliometrics#206]
The [following paper](https://www.scopus.com/record/display.uri?eid=2-s2.0-85100910856&origin=resultslist) with scopus ID `85100910856` was published in 2021, as can be seen on the scopus page, but has citations dated before 1900:

```
>>> res = CitationOverview(identifier=["85100910856"], start=1900)
>>> print(res.pcc)
[1]
```

**Comment by Michael-E-Rose** [comment]
I cannot replicate this. For me this looks like

```
>>> res = CitationOverview(identifier=["85100910856"], start=1900)
>>> print(res.pcc)
[0]
```

However, it actually does happend that citation occur before the document is published:
1. Citations from the year or the two years before is normal IMO as the publication lag can be very lengthy
2. Books are indexed by year of online publication, not actual publication; Actual citations thush look like they occurred before Scopus says the book was published
3. There are also errors in the publication date information on Scopus; if this is the case, have them corrected via the [Scopus web form](https://service.elsevier.com/app/contact/supporthub/scopuscontent/).

**Comment by raffaem** [comment]
I confirm that I continue to obtain `[1]' and with `refresh=True` I now obtain `0`.

Why was the data before the refresh wrong?

---

What do you mean by 

> Books are indexed by year of online publication, not actual publication

?

**Comment by Michael-E-Rose** [comment]
I cannot say why the data was wrong before the refresh. Perhaps there was a wrong entry on Scopus (i.e., a wrong publication year of a citing document) and they fixed it since you first requested the information.

----

I meant "publication year". For some reason beyond my understanding, the coverDate of a book or book chapter in Scopus is the year the book or book chapter got published _online_. All other people would use the year the book was actually published.

That's why [Wassily Leontief](https://www.scopus.com/authid/detail.uri?authorId=6603558540) (Economics Nobel Prize in 1973) has four publications (books and book chapters) published after his death in 1999.
