### ISSUE TITLE
AbstractRetrieval: Author IDs in FULL view and number of references in REF view

### ISSUE THREAD

**Issue by egonzales2000** [pybliometrics-dev/pybliometrics#271]
Hi, 

I was wondering why the FULL view in the AbstractRetrieval doesnt provide any information on the authors' ids of a reference.. The list shown [here ](https://dev.elsevier.com/sc_abstract_retrieval_views.html) is not really helpful. When switching to the REF view I get the ids, yet, I have only max. 40 entries for the references... 

Any help is much appreciated.

**Comment by Michael-E-Rose** [comment]
This is something only Scopus can tell you...

I raised this issue many times. But my feeling is that developing the Scopus API is not high on the agenda.

What I typically do to circumvent this information is: I use the REF view information if there are fewer than 41 references, an otherwise I source the cited documents if the type of the reference in the FULL view is resolved (non-resolved documents are not indexed).

**Comment by egonzales2000** [comment]
Hi, Thanks for your quick reply. My current approach is to paginate the results with the REF view. The problem here, however, is that only one slice of data is stored in the cache and with the cached data the startref and refcount information doesn't work. Using refresh=True solves the problem.....

**Comment by egonzales2000** [comment]
Found a nasty solution: I simply change line 44 in the retrieval.py to:             

stem = str(identifier.replace('/', '_')) + "_" + str(kwds['startref'])

so that files now have the startref info in their filename. This however will lead to problems if you dont pass the the startref info.
