### ISSUE TITLE
LitStudy - Scopus400 Error: Exceeds the maximum number allowed for the service level

### ISSUE THREAD

**Issue by SS159** [pybliometrics-dev/pybliometrics#300]
When using the LitStudy package, which calls on pybliometrics to enrich paper metadata via Scopus, 'Scopus400 Error: Exceeds the maximum number allowed for the service level' is being returned. The enforced maximum seems to be only 180 papers - is this correct? Is there a problem with my API key? ([00f8fa3132f9ffe91592b3fade8c10c6])

![image](https://github.com/pybliometrics-dev/pybliometrics/assets/60474063/65ceb5ba-ce65-49ff-94a2-e7690ab38ea2)

![image](https://github.com/pybliometrics-dev/pybliometrics/assets/60474063/5f60cce4-8bd4-4f0c-8222-46402c4da72e)

**Comment by Michael-E-Rose** [comment]
The most likely cause is an insufficient subscription of your institution. See https://pybliometrics.readthedocs.io/en/stable/access.html for details.
Initially I was just confused bco the error message.

**Comment by FabianEUR** [comment]
Hi,

I have the same problem - ScopusError400 - when trying to refine metadata using the litstudy package. There's no error when on my university's campus and connected to the wifi. However, when connected to my university's VPN via FortiClient when not on campus, I get this error. I can still manually download articles/export metadata from Scopus but not use the refine_scopus function. I saw on the configuration page that I have to add the [Proxy] section but that hasn't changed the outcome. I've used "http://127.0.0.1:1234" as the http and https address. Should I replace this with the IP address that the VPN client connected to my university gives me? It is only one IP address and doesn't end in ":1234". 


My code:

![image](https://github.com/pybliometrics-dev/pybliometrics/assets/155644355/01ca5d73-a104-4aad-a11a-38f609fc42e5)

**The error:**
runfile('C:/Users/xxx/.spyder-py3/litstudy_RS_Div.py', wdir='C:/Users/xxx/.spyder-py3')
Creating config file at C:\Users\xxx\.config\pybliometrics.cfg with default paths...
Please enter your API Key(s), obtained from http://dev.elsevier.com/myapikey.html.  Separate multiple keys by comma:
xxxxxxxxxxxxxxxxxx
API Keys are sufficient for most users.  If you have an InstToken, please enter the token now; otherwise just press Enter:

Configuration file successfully created at C:\Users\xxx\.config\pybliometrics.cfg
For details see https://pybliometrics.rtfd.io/en/stable/configuration.html.
2023 papers loaded from Scopus
  0%|          | 2/2023 [00:00<04:36,  7.31it/s]
Traceback (most recent call last):

  File C:\ProgramData\anaconda3\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\xxx\.spyder-py3\litstudy_rs_div.py:30
    docs_scopus, docs_not_found = litstudy.refine_scopus(docs_scopus)

  File ~\AppData\Roaming\Python\Python311\site-packages\litstudy\sources\scopus.py:248 in refine_scopus
    return docs._refine_docs(callback)

  File ~\AppData\Roaming\Python\Python311\site-packages\litstudy\types.py:53 in _refine_docs
    new_doc = callback(doc)

  File ~\AppData\Roaming\Python\Python311\site-packages\litstudy\sources\scopus.py:236 in callback
    response = ScopusSearch(query, view="STANDARD", download=False)

  File ~\AppData\Roaming\Python\Python311\site-packages\pybliometrics\scopus\scopus_search.py:206 in __init__
    Search.__init__(self, query=query, api='ScopusSearch', count=count,

  File ~\AppData\Roaming\Python\Python311\site-packages\pybliometrics\scopus\superclasses\search.py:62 in __init__
    Base.__init__(self, params=params, url=URLS[api], download=download,

  File ~\AppData\Roaming\Python\Python311\site-packages\pybliometrics\scopus\superclasses\base.py:66 in __init__
    resp = get_content(url, api, params, *args, **kwds)

  File ~\AppData\Roaming\Python\Python311\site-packages\pybliometrics\scopus\utils\get_content.py:116 in get_content
    raise errors[resp.status_code](reason)

Scopus400Error: Exceeds the maximum number allowed for the service level`

---

Any help is appreciated and am happy to supply more information! Thanks
