### ISSUE TITLE
Support querying the Citations Overview API with multiple EIDs at once

### ISSUE THREAD

**Issue by aieri** [pybliometrics-dev/pybliometrics#76]
The current CitationOverview class makes requesting citation reports for a single document easy, but its strict one-query-per-document structure makes it cumbersome to fetch non-trivial amounts of data.
Since scopus allows for adding a multitude of &scopus_id= parameters to the citation overview queries, being able to request multiple documents at once would drastically improve the efficiency of querying scopus. This is particularly true when factoring in the API limitations of (currently) 20k request per week per enabled API key (at only 3 requests / second).

I have thought a bit about the problem, and since the CitationOverview class doesn't really lend itself to representing a multitude of results (well, not at all), I think the best approach would be to add a very non-OO function to seed the cache. A generic description could be:
* given a list of EIDs,
* construct a CitationOverview API query (this is easy since [requests natively supports lists as parameter values](http://docs.python-requests.org/en/master/user/quickstart/#passing-parameters-in-urls)),
* use scopus.utils.download to retrieve the whole set of results at once,
* split the results saving one cache file per requested document (retaining the EID-as-filename structure)

After a first seeding run, CitationOverview classes could then be quickly instantiated from the cache.

I think the above would be the most natural way to implement a bulk downloader without having to mess with the CitationOverview class, or having to duplicate most of it into a new and weird CitationOverviewBulk class.

I could try to take a stab at the above in the next few days, do you think it would be the right approach?

**Comment by aieri** [comment]
Happy new year @Michael-E-Rose!

I agree, it would be nice to do this for all classes (where allowed by the Scopus API), and to do it properly.

As I need to collect quite a bit of data _now_, I have however written a [bulk downloader](https://github.com/aieri/scopus/blob/bulkcitations/scopus/utils/bulkreports.py) for my specific use case. It is perhaps not exactly the most elegant solution, but it is good enough for what I have to do.

Things I have learned:
* splitting the returned json to simulate querying papers one by one is possible, except for the hindex value. I do not see any way to deduce the hindex of the individual papers from the aggregated one.
* there seems to be a hard limit of 25 documents per query. Scopus simply returns 400 when you ask for 26 documents or more. This is far less than I had hoped, but still, a 25x speed improvement is nothing to scoff at!
* I have implemented chunking in my own script to handle the 25 items limit. I did not do it within the downloader itself because I wanted to periodically log the download status, but moving the code over into the bulk downloader would be very simple.

I am not submitting a PR for my bulk downloader as it is not a generic solution, but feel free to take a look in case parts of it could be useful for scopus 2.0

**Comment by ste210** [comment]
Hi guys,
I agree that this would be quite an improvement. I was trying to draft something analogous in https://github.com/sosia-dev. Maybe adding something obvious, but, have you considered also these issues:
- it would be nice to have an additional layer at the beginning to check first if each single file is already in the cache, later search for the remaining elements in a combined query, and recombine everything at the end. Otherwise combined queries will not be found again in cache, unless they do not completely overlap
- it would probably not work for complex queries (anything more than a list of 'OR' conditions), so, I guess it may require a parallel option to the existing one

**Comment by Michael-E-Rose** [comment]
Hi everybody, good to see this issue moving on.
Just a first reaction: The 25 limit is indeed hard-coded in https://github.com/scopus-api/scopus/blob/master/scopus/scopus_search.py#L107 and the following line. Since we generally download the complete view, 25 is the maximum. We _could_ set the limit depending on the view someone wants to download. For me it was always more important to have more data rather than to be quick.

As for the bulk downloader concpet: I think a super-class is more favorable. It would take a list of say authors or articles, check which ones are available, download them, split them, and save them individually. I guess this is more transparent then giving the normal search classes a query which first has to be checked whether the query is only "and" or more complex.

**Comment by fabiosangregorio** [comment]
Hi @Michael-E-Rose,
I too would need to query multiple EIDs at once with AuthorRetrieval, which is supported by the Scopus API.
Can I ask if there's been any progress on this issue?

**Comment by Michael-E-Rose** [comment]
No, nothing new yet. It's a bit more challenging than other tasks so far.

**Comment by IvanSterligov** [comment]
Hello, any hope to see this implemented, or is this issue effectively abandoned? Perhaps there are any forks? 

just had to migrate to raw API because of speed issues and quota exhaustion both arising from inability to query multiple publications (I need yearly counts with and w/o self cites for ca 380k papers).  Would be great to be able to send them in 25-packs via Pybliometrics to get 25x speed increase +25x less quota, but my python skills are too low to mess with your code

Nevertheless many thanks for a great wrapper! Other modules work great

**Comment by Michael-E-Rose** [comment]
Except for @aieri's solution I'm not aware of forks. Back then the name of this package was still "scopus".

Looking at the [developer docs of the Citation Overview API](https://dev.elsevier.com/documentation/AbstractCitationAPI.wadl) again I note parameters `scopus_id`, `doi`, `pii` and `pubmed_id`.  Apparently one would retrieve joint yearly citation counts for a bunch of documents. I will experiment a little in the coming weeks and think about how one can store this.

I think it's not the initial idea of this issue, but delivers a quick and easily useable solution in the existing framework. Use cases I can think of right now include an author's entire citation trajectory.

**Comment by Michael-E-Rose** [comment]
Turns out I really missunderstood the idea of this issue all the years.

The `CitationOverview()` works very differently now, accepting a list of up to 25 identifiers of the same type (Scopus ID, DOI, PII or Pubmed ID).  Unlike in the initial proposal, all the information are stored in just one file.  The current parameter `eid` is deprecated and will be removed in a future release.
