### ISSUE TITLE
Add a progress bar to download function?

### ISSUE THREAD

**Issue by crew102** [pybliometrics-dev/pybliometrics#85]
It would be nice if `download()` could provide an indication of its progress, especially for large result sets that may take awhile to download. I don't know if this can be done cleanly without having to rely on an external lib like https://github.com/tqdm/tqdm, but either way I think it's worth considering.

**Comment by Michael-E-Rose** [comment]
This can be done quite easily with
```
def print_progress(iteration, total, length=50):
    """Print terminal progress bar."""
    percent = 100 * (iteration / float(total))
    filled_len = int(length * iteration // total)
    bar = '█' * filled_len + '-' * (length - filled_len)
    print('\rProgress: |{}| {:.2f}% Complete'.format(bar, percent), end='\r')
    if iteration == total:
        print()
```
I use a function like this all the time.  But a function like this only makes sense for downloads with Search classes, where each iteration corresponds to a chunk of data.  For the Retrieval classes, this won't make sense, since we're downloading one file only.

I think is quite easy to implement this.  Wanna go ahead?  It should in any case be optional to print this (using a verbose parameter that is by default `False`).

**Comment by crew102** [comment]
Sure thing, will do. PR on the way.

**Comment by crew102** [comment]
Actually it probably makes sense to handle #87 first. Once that's merged I'll add the progress bar.

**Comment by Michael-E-Rose** [comment]
Feature was added in 1cfd2fff897e43f7e75a2b9a81020b3df415af34.
